apiVersion: v1
kind: Service
metadata:
  name: hightech-service
  labels:
    app: hightech-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hightech